question1 = input("Enter your name: ")
question2 = input("What state are you from: ")
print("I can guess your birth year...")
print("Should I...")
question3 = input("Y-yes/N-no: ")
question4 = int(input("What's your age then________: "))
print(2024-question4)
print("Good...")
question5 = int(input("Enter how much you want God to give you: "))
question6 = input("How do you think this money you typed can change your life???...: ")
print("God suprised you and gave you this amount of money, if you have faith and believe this money, then its yours in jesus name" )
print(question5/2)
print("Thanks for excercising that little faith of yours, see you later...")
print("Danfix Studio")
