print("Pattern A:")
print("*")
print("**")
print("***")
print("****")
print("*****")
print()

print("Pattern B:")
print("    *    ")
print("   ***   ")
print("  *****  ")
print(" ******* ")
print("*********")
print() 

print("Pattern C:")
print("*****")
print("****")
print("***")
print("**")
print("*")
print() 

print("Pattern D:")
print("    *    ")
print("   ***   ")
print("  *****  ")
print(" ******* ")
print("*********")
print(" ******* ")
print("  *****  ")
print("   ***   ")
print("    *    ")

